/**
 * OpenFishTools Web-Tools Bundler
 * Compiles all modular tools and method engines into a single distribution bundle.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const TOOLS_DIR = path.join(ROOT_DIR, 'tools');
const DIST_DIR = path.join(ROOT_DIR, 'dist');

if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

// Ordered list of files to concatenate into the bundle
const BUNDLE_FILES = [
    // 1. Method Main Engines
    path.join(TOOLS_DIR, 'Method', 'finalize.js'),
    path.join(TOOLS_DIR, 'Method', 'compress.js'),

    // 2. Method Items (Patcher Suites)
    path.join(TOOLS_DIR, 'Method', 'item', 'streamshield.js'),
    path.join(TOOLS_DIR, 'Method', 'item', 'binarypatch.js'),
    path.join(TOOLS_DIR, 'Method', 'item', 'FRYMethod.js'),
    path.join(TOOLS_DIR, 'Method', 'item', 'fpspatch.js'),
    path.join(TOOLS_DIR, 'Method', 'item', 'wmvpatch.js'),
    path.join(TOOLS_DIR, 'Method', 'item', 'emergencymethod.js'),

    // 3. TikTok Tools
    path.join(TOOLS_DIR, 'tiktok', 'tiktok-quality-tool.js'),
    path.join(TOOLS_DIR, 'tiktok', 'tiktok-downloader-tool.js'),
    path.join(TOOLS_DIR, 'tiktok', 'tiktok-stats-tool.js'),

    // 4. Video & Audio Tools
    path.join(TOOLS_DIR, 'video', 'video-compressor-tool.js'),
    path.join(TOOLS_DIR, 'video', 'video-interpolation-tool.js'),
    path.join(TOOLS_DIR, 'video', 'audio-extractor-tool.js'),
    path.join(TOOLS_DIR, 'video', 'image-sequence-tool.js'),

    // 5. AI & Enhancement Tools
    path.join(TOOLS_DIR, 'ai', 'upscale-gpu-enhancer.js'),
    path.join(TOOLS_DIR, 'ai', 'upscale-tool.js'),
    path.join(TOOLS_DIR, 'ai', 'rembg-tool.js'),

    // 6. Converters & XML Helpers
    path.join(TOOLS_DIR, 'converters', 'ae-to-am-beatmark-tool.js'),
    path.join(TOOLS_DIR, 'converters', 'fivemb-generator-tool.js')
];

const banner = `/**
 * OpenFishTools Web-Tools Unified Bundle
 * Version: ${require('../package.json').version || '1.0.0'}
 * Build: ${new Date().toISOString()}
 * 
 * Auto-generated by OpenFishTools Web-Tools Bundler.
 * Contains: 8 Method Engines + 12 Core Video, Audio, TikTok, AI & XML Tools.
 */
`;

console.log('Building web-tools bundle...');

let bundleContent = banner + '\n(function() {\n  "use strict";\n\n';

let fileCount = 0;
for (const filePath of BUNDLE_FILES) {
    if (!fs.existsSync(filePath)) {
        console.warn(`Warning: File not found: ${filePath}`);
        continue;
    }
    const rel = path.relative(ROOT_DIR, filePath);
    console.log(`  + [Include] ${rel}`);
    const code = fs.readFileSync(filePath, 'utf8');
    bundleContent += `\n/* === Start: ${rel} === */\n`;
    bundleContent += code;
    bundleContent += `\n/* === End: ${rel} === */\n`;
    fileCount++;
}

bundleContent += '\n})();\n';

const outBundlePath = path.join(DIST_DIR, 'web-tools.bundle.js');
fs.writeFileSync(outBundlePath, bundleContent, 'utf8');

const stats = fs.statSync(outBundlePath);
const sizeKb = (stats.size / 1024).toFixed(2);
console.log(`\nBundle created successfully:`);
console.log(`  File: dist/web-tools.bundle.js`);
console.log(`  Modules: ${fileCount} files`);
console.log(`  Size: ${sizeKb} KB`);

// Copy workers to dist/workers/
const workersSrcDir = path.join(TOOLS_DIR, 'workers');
const workersDistDir = path.join(DIST_DIR, 'workers');
if (fs.existsSync(workersSrcDir)) {
    if (!fs.existsSync(workersDistDir)) {
        fs.mkdirSync(workersDistDir, { recursive: true });
    }
    const workerFiles = fs.readdirSync(workersSrcDir);
    for (const f of workerFiles) {
        fs.copyFileSync(path.join(workersSrcDir, f), path.join(workersDistDir, f));
        console.log(`  + [Worker] dist/workers/${f}`);
    }
}

// Generate version manifest
const versionManifest = {
    version: require('../package.json').version || '1.0.0',
    buildDate: new Date().toISOString(),
    modules: fileCount,
    tools: [
        'tool-tiktok-patcher',
        'tool-video-compressor',
        'tool-audio-extractor',
        'tool-image-sequence',
        'tool-5mb-generator',
        'tool-ae-am-beatmark',
        'tool-upscale-enhancer',
        'tool-video-interpolation',
        'tool-remove-background',
        'tool-tiktok-stats',
        'tool-tiktok-downloader'
    ]
};

fs.writeFileSync(path.join(DIST_DIR, 'version.json'), JSON.stringify(versionManifest, null, 2), 'utf8');
console.log(`  + [Manifest] dist/version.json\nBuild finished!`);
